version: '3.9'

services:
  db:
    image: postgres:13.0-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: bookstore_dev
      POSTGRES_PASSWORD: bookstore_dev
      POSTGRES_DB: bookstore_dev_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
    container_name: bookstore
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    depends_on:
      - db

volumes:
  postgres_data:
